export { default as backgroundImg } from './background.jpg'
export { default as banner } from './banner.jpg'
export { default as sliderBannerCashback } from './slider-banner-1.png'
export { default as sliderBannerCar } from './slider-banner-2.png'
export { default as sliderBannerJackpot } from './slider-banner-3.png'
